Feature/quickbid
mojitoinc/mojito-reference-app pull request #5
Opened 2022-01-18 14:59 UTC by bejarano-tech

2022-01-20 10:22 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +  const showQuickBid = () => {
Why is this a function instead of a variable if you are always calling it below?

    const showQuickBid = mojitoLotData.currentBid.marketplaceUser.id !== profile?.me?.id && isAuthenticated && mojitoLotData.bidView.isDuringSale;

2022-01-20 10:24 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +    Object.assign({}, mojitoLotData.currentBid , data.getMarketplaceAuctionLot.currentBid)
This doesn't do anything. What are you trying to achieve?

2022-01-20 10:25 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +    background-color: #ff00ff;
Didn't we introduce a theme already in the reference app? Maybe this color and some of the values below (`border-radius`, `color`, fonts) should come from there.

2022-01-20 10:26 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +                mojitoLotData.currentBid?.amount
mojitoLotData.currentBid?.amount || 0

2022-01-20 10:28 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +            {mojitoLotData.bidView.isPostSale && mojitoLotData.currentBid ? (
You are accessing `currentBid` in a few different places here, considering doing `const { currentBid } = mojitoLotData` above.

2022-01-20 10:29 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +          handleCustomBid={() => {}}
Something might be missing here. Otherwise, just make this prop optional.

2022-01-20 10:29 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +          handleClose={() => setShowQuickBidModal(false)}
I would consider wrapping this callbacks in `useCallback` above. Maybe not for all of them (like a simple button), but it might be worth for a larger / more complex component like this modal, to avoid making it re-render.

2022-01-20 10:30 UTC, Danziger commented on src/components/lot/QuickBidModal.tsx
> +  max-width: 660px;
Theme? Just asking, not sure if this value already matches one of the breakpoints or if it's used in other places.

2022-01-20 10:32 UTC, Danziger commented on src/components/lot/QuickBidModal.tsx
> +  color: #FF00FF;
Again, theme? Maybe review all styles and look for things that are already defined or should be defined in the theme, we should avoid adding more hardcoded values after Fernando (I think it was Fernando) already did a lot of work to move most of that to a theme.

2022-01-20 10:32 UTC, Danziger commented on src/components/lot/QuickBidModal.tsx
> +  const [error, setError] = useState<any>(null);
Missing type.

2022-01-20 10:32 UTC, Danziger commented on src/components/lot/QuickBidModal.tsx
> +      console.log(e);
Should this be here?

2022-01-20 10:33 UTC, Danziger commented on src/components/lot/QuickBidModal.tsx
> +  const onCustomBid = () => {
Consider using `useCallback`.

2022-01-20 10:33 UTC, Danziger commented on src/pages/lots/[slug].tsx
> +    background-color: #ff00ff;
Theme.

2022-01-20 10:34 UTC, Danziger commented on src/pages/lots/[slug].tsx
> +            handleClose={() => setShowQuickBidModal(false)}
Consider using `useCallback`.

2022-01-20 10:34 UTC, Danziger requested changes
I added a bunch of comments, PTAL.

2022-01-20 15:03 UTC, bejarano-tech commented on src/components/grid/LotGridItem.tsx
> +    Object.assign({}, mojitoLotData.currentBid , data.getMarketplaceAuctionLot.currentBid)
This is updating the mojitoLotData.currentBid information based on the new data available brought through websocket subscription

2022-01-24 15:34 UTC, bejarano-tech commented on src/components/lot/QuickBidModal.tsx
> +  color: #FF00FF;
Sure, i will review all styles. Was Juan Pablo who work on the theming :).

2022-01-24 15:49 UTC, bejarano-tech commented on src/components/lot/QuickBidModal.tsx
> +      console.log(e);
Yes, after the placeBid we need to close the modal.

2022-01-31 10:15 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +  const showQuickBidOnChange = useCallback(() => { setShowQuickBidModal(!showQuickBidModal) }, [showQuickBidModal]);
You don't need the `{}` here. Also, use the previous state value instead of passing it as a prop:

    const showQuickBidOnChange = useCallback(() => setShowQuickBidModal(prevShowQuickBidModal => !prevShowQuickBidModal), []);

2022-01-31 10:16 UTC, Danziger commented on src/components/grid/LotGridItem.tsx
> +    Object.assign({}, currentBid , data.getMarketplaceAuctionLot.currentBid)
What is this doing?

2022-01-31 10:17 UTC, Danziger commented
@bejarano-tech I've added a couple additional comments, but I see some of the previous ones hasn't been resolved. PTAL

2022-02-03 15:28 UTC, jpirazusta commented on src/components/lot/QuickBidModal.tsx
> +);
```suggestion
const ModalTitle = styled.h3`
  margin-top: 0;
  margin-bottom: 40px;
  text-align: center;
  font-size: 24px;
`;
```

2022-02-03 15:28 UTC, jpirazusta commented on src/components/lot/QuickBidModal.tsx
> +);
```suggestion
const ModalSubTitle = styled.h4`
  margin-top: 0;
  margin-bottom: 14px;
  text-align: center;
  font-size: 32px;
`;
```

2022-02-03 15:29 UTC, jpirazusta commented on src/components/lot/QuickBidModal.tsx
> +);
You can check the `fonts` section of the theme

2022-02-03 15:30 UTC, jpirazusta commented on src/components/lot/QuickBidModal.tsx
> +  color: #29ABE2;
Same here. Take the color from the theme also

2022-02-03 15:47 UTC, jpirazusta commented on src/components/lot/QuickBidModal.tsx
> +);
```suggestion
const ButtonsContainer = styled.div`
  display: flex;
  justify-content: space-evenly;
  margin-top: 44px;
  margin-bottom: 30px;
  grid-gap: 24px;
`;
```
Also, why the `grid-gap` in a flex container?

2022-02-03 15:49 UTC, jpirazusta commented on src/components/lot/QuickBidModal.tsx
> +  ${theme.down(theme.breakpoints.md)} {
```suggestion
  text-align: center;
  
  ${theme.down(theme.breakpoints.md)} {
```

2022-02-03 15:49 UTC, jpirazusta commented on src/components/lot/QuickBidModal.tsx
> +  ${theme.down(theme.breakpoints.md)} {
```suggestion
  height: 60px;
  
  ${theme.down(theme.breakpoints.md)} {
```

2022-02-03 17:27 UTC, jpirazusta commented on src/pages/lots/[slug].tsx
> +    font-size: 16px;
Can use the theme here as well

2022-02-04 13:31 UTC, jpirazusta commented on src/pages/lots/[slug].tsx
> +  const showQuickBidOnChange = useCallback(() => { setShowQuickBidModal(!showQuickBidModal) }, [showQuickBidModal]);
Here we can apply the same as above, at Dani's comment

2022-02-04 13:32 UTC, jpirazusta commented on src/pages/lots/[slug].tsx
> +  let { data: mojitoLotData } = useMojito(EMojitoQueries.oneLot, {
Why not `const`?

2022-02-04 13:33 UTC, jpirazusta commented on src/pages/lots/[slug].tsx
> +              </>
The fragment is not needed here

2022-04-14 13:02 UTC, Dmckinney821 commented
Do we still need this PR? @bejarano-tech

2022-04-18 16:48 UTC, bejarano-tech commented
> Do we still need this PR? @bejarano-tech

Hi Dan, i'm going to test this to see if have sense to keep it.

2022-05-03 13:59 UTC, bejarano-tech commented
I close this pr because is too much behind from the current reference app implementation.

2022-05-03 13:59 UTC, closed without merging